=head1 NAME

Mojolicious::Plugin::MysqlViewerCheap

=head1 SYNOPSYS

    # Mojolicious::Lite
    plugin 'mysql_viewer_cheap' dbh => $dbh;

    # Mojolicious
    $app->plugin('mysql_viewer_cheap', dbh => $dbh);

    # Access
    http://localhost:3000/mysqlviewer

=head1 DESCRIPTION

Plugable mojolicious application to see MySQL database information.

This module have the following features.

=over 4

=item *

You can see all table definition.

=item *

You can specify talbe and select top 1000 rows.

=item *

You can see primary key, null allowed column, and database engine of all tables.

=back

=head1 INSTALL

Mojolicious::Plugin::MysqlViewerCheap need the following module.

    cpan DBIx::Custom;
    cpan Validator::Custom;

And you copy Mojolicious::Plugin::MysqlViewerCheap source code
to the following place.

    lib/Mojolicious/Plugin/MysqlViewerCheap.pm

lib must be included in @INC.

=head1 CAUTION

I want a perl tool like phpMyAdmin. but I don't have the time to create it.
so this tool is not so good to use.
but i think this is good example of Mojolicious plugin.
