=head1 NAME

Mojolicious::Plugin::MySQLViewerLite

=head1 SYNOPSYS

    # Mojolicious::Lite
    plugin 'MySQLViewerLite', dbh => $dbh;

    # Mojolicious
    $app->plugin('MySQLViewerLite', dbh => $dbh);

    # Access
    http://localhost:3000/mysqlviewerlite

=head1 DESCRIPTION

Show MySQL database information.
This is L<Mojolicious> plugin.

L<Mojolicious::Plugin::MySQLViewerLite> have the following features.

=over 4

=item *

You can see all table definition.

=item *

You can specify talbe and select top 1000 rows.

=item *

You can see primary key, null allowed column, and database engine of all tables.

=back

=head1 INSTALL

Mojolicious::Plugin::MySQLViewerLite need the following module.

  DBIx::Custom;
  Validator::Custom;

And you copy Mojolicious::Plugin::MySQLViewerLite source code
to the following place.

    lib/Mojolicious/Plugin/MySQLViewerLite.pm
